### ISSUE TITLE
Can we do the same to validate the description of the pull request 

### ISSUE THREAD

**Issue by bheemvennapureddy** [joshjohanning/azdo_commit_message_validator#61]
Can we validate the description of the pullrequest to make sure the user story is linked in the description instead of the commit message ?

**Comment by joshjohanning** [comment]
Hi @bheemvennapureddy! Yes, great idea. I just added this in a branch if you want to test it out

```yml
      - name: Azure DevOps Pull Request Validator
        uses: joshjohanning/azdo_commit_message_validator@only-link-in-pr
        with:
          check-pull-request: true
          check-commits: false
```

This seems to work based on my tests :) 

- fail since I didn't link: https://github.com/joshjohanning-org/azdo-commit-message-enforcer-testing/pull/11
- succeed b/c link in pr title: https://github.com/joshjohanning-org/azdo-commit-message-enforcer-testing/pull/12
- succeed b/c link in pr body: https://github.com/joshjohanning-org/azdo-commit-message-enforcer-testing/pull/14
- succeed b/c link in pr title + body: https://github.com/joshjohanning-org/azdo-commit-message-enforcer-testing/pull/13
