### ISSUE TITLE
Support disabling comment on failure

### ISSUE THREAD

**Issue by joshjohanning** [joshjohanning/azdo_commit_message_validator#76]
Already have the input:

```
  comment-on-failure:
    description: "Comment on the pull request if the action fails"
    required: true
    default: true
```

But I did not implement in composite action.  Or document in readme?
